-- Table to store current admin details
CREATE TABLE IF NOT EXISTS admins (
    user_id TEXT PRIMARY KEY,
    dept_id INT,
    user_type TEXT,
    dept_mail_id TEXT,
    department_name TEXT,
    dept_alias_name TEXT,
    last_login TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Table to log login/logout events
CREATE TABLE IF NOT EXISTS admin_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT REFERENCES admins(user_id),
    action TEXT NOT NULL, -- 'LOGIN' or 'LOGOUT'
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add RLS policies (Optional but recommended)
ALTER TABLE admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_logs ENABLE ROW LEVEL SECURITY;

-- Allow public read/write for now (since we handle auth in API)
-- In production, you'd want stricter policies
CREATE POLICY "Enable read access for all users" ON admins FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON admins FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for all users" ON admins FOR UPDATE USING (true);

CREATE POLICY "Enable read access for all users" ON admin_logs FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON admin_logs FOR INSERT WITH CHECK (true);
